Вариант 7 Глазунов Даниил ПИ19-4

In [24]:
import numpy as np
import pandas as pd
from scipy.optimize import Bounds, linprog
np.set_printoptions(suppress=True)

In [25]:
C = np.matrix([[10, 3, 6, 10, 4],[16,12,8,13,7],[5,9,15,18,22]])
print(C)

[[10  3  6 10  4]
 [16 12  8 13  7]
 [ 5  9 15 18 22]]


In [26]:
a1=250
a2=400
a3=280

In [27]:
A = np.array([a1, a2, a3])

In [28]:
b1=160
b2=110
b3=220
b4=270
b5=170

In [29]:
B = np.array([b1, b2, b3, b4, b5])

In [30]:
N = len(A)
M = len(B)

In [31]:
df = pd.DataFrame(C, columns=B, index=A)
df.columns.name = 'aᵢ \\ bⱼ'
df

aᵢ \ bⱼ  160  110  220  270  170
250       10    3    6   10    4
400       16   12    8   13    7
280        5    9   15   18   22

In [32]:
if sum(A) == sum(B):
    print('Задача закрытого типа')
else:
    print('Задача открытого типа')

Задача закрытого типа


План перевозки груза

In [33]:
P = np.zeros_like(C)
INF = 1_000_000_007
C_ = C.copy()
A_ = A.copy()
B_ = B.copy()
i = 0
j = 0

In [34]:
while not np.all(C_ == INF):
    i, j = np.unravel_index(C_.argmin(), C_.shape)
    P[i][j] = min(A_[i], B_[j])
    if A_[i] <= B_[j]:
        C_[i].fill(INF)
        B_[j] -= A_[i]
        A_[i] = 0
    else:
        C_[:, j].fill(INF)
        A_[i] -= B[j]
        B_[j] = 0    
if np.count_nonzero(P) != N + M - 1:
    print('Опорный план вырожденный')
else:
    print('Опорный план невырожденный')

F = 0
for i in range(N):
    for j in range(M):
        F += C[i][j] * P[i][j]
print('Полученный план перевозки груза:\n', P)
print('Значение целевой функции для этого опорного плана F =', F)

IndexError: index 1 is out of bounds for axis 0 with size 1

Оптимальный план перевозки груза

In [35]:
#A_ma1 - матрица коэфициентов
#x <= B_ma1 (E @ x <= A)
A_ma1 = np.array([[1 if i in range(j*M, M*(j+1)) else 0 for i in range(N*M)] for j in range(N)])
B_ma1 = A

#A_ma2 - матрица коэфициентов
#x = B_ma2 (E @ x = B)
A_ma2 = np.array([[1 if i % M == j else 0 for i in range(N*M)] for j in range(M)])
B_ma2 = B

res = linprog(C.flatten(), A_ma1, B_ma1, A_ma2, B_ma2, options={'disp': True})
X = res.x.round(3).reshape(N, M)
F_min = res.fun.round(3)

Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 158.0               
0.1509881089111     0.1509881089111     0.1509881089111     0.8591091387928  0.1509881089111     942.1645814691      
0.05267211670766    0.05267211670766    0.05267211670765    0.6696339665225  0.05267211670768    1921.649837504      
0.007971459156631   0.007971459156632   0.00797145915663    0.8522187172698  0.007971459156635   5207.102730375      
0.001232434474034   0.001232434474034   0.001232434474033   0.8633686608889  0.001232434474034   7039.055211688      
0.0001069764105818  0.0001069764105819  0.0001069764105824  0.9363993343587  0.0001069764105733  7503.823376994      
7.694919008545e-09  7.694919011674e-09  7.694918279086e-09  0.999935126711   7.694912763143e-09  7549.996639701      
Optimization terminated successfully.
         Current fu

In [36]:
print('Оптимальный план перевозки груза:')
X

Оптимальный план перевозки груза:


array([[  0.   ,   0.   ,   0.   , 138.787, 111.213],
       [  0.   ,   0.   , 220.   , 121.213,  58.787],
       [160.   , 110.   ,   0.   ,  10.   ,   0.   ]])

In [37]:
print('Оптимальная стоимость перевозки:')
F_min

Оптимальная стоимость перевозки:


7549.997